spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.131:3306/mall?characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 192.168.75.131  #redis服务器地址
    database: 0 #redis数据库索引（默认为0）
    port: 6379  #redis服务器连接端口
    password: #redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      authCode: 120 # 验证码超时时间

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0